version: "3.7"

networks:
  web:
    external: true

services:
  frontend:
    restart: always
    networks:
      - web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.sidecar.laravel.pt.test`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
